[build]
  command = "pip install -r requirements.txt && pip install flask[async]"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.11" 