[build]
  command = "pip install -r requirements.txt"
  publish = "."

[functions]
  node_bundler = "esbuild"
  included_files = [
    "app.py",
    "database.py",
    "models.py",
    "services.py",
    "templates/**",
    "static/**"
  ]

[[redirects]]
  from = "/*"
  to = /.netlify/functions/app
  status = 200

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18" 